# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da5d9da9f16c3f199e1512965862f0fc450b3219e6803d93853ba7254228b8acac9e113075419864a7e0bc06cb954a7e41a3dfafd050eee4a679a640f8b58e2

test:
  secret_key_base: ff4ac1335da7be73e5d241670c3da170fca63e3965e8852b525b9f6fb9beacfe44d559051c26dd9fa6ab1c5a4c5f36fb8e37239c223226828df82009974442de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
