# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pulbished_date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
